use_frameworks!

platform :ios, '9.0'

target 'ZHNetworking_Example' do
  pod 'ZHNetworking', :path => '../'

  target 'ZHNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
